# Generated by Django 4.0.6 on 2022-08-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='licencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Cedula', models.FloatField()),
                ('cargo', models.CharField(max_length=50)),
                ('Fecha_Permiso', models.FloatField()),
                ('Total_horas', models.FloatField()),
                ('Motivo_Permiso', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'licencia',
                'verbose_name_plural': 'licencias',
            },
        ),
    ]
