# Generated by Django 4.0.6 on 2022-08-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('texto_1', models.CharField(max_length=500)),
                ('texto_2', models.CharField(max_length=500)),
                ('texto_3', models.CharField(max_length=500)),
            ],
        ),
    ]
