# Generated by Django 4.0.6 on 2022-08-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
