# Generated by Django 4.0.6 on 2022-08-31 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_datos_creation_date_alter_datos_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos',
            options={'verbose_name': 'dato', 'verbose_name_plural': 'datos'},
        ),
    ]
